### ISSUE TITLE
Carbonite 3.3.5 - Teleport doesn't appear. No hook to map.

### ISSUE THREAD

**Issue by StygianTheBest** [karlbunch/LordKator_TrinityMagic#1]
The text change from Goto to Teleport doesn't work on my Carbonite 3.3.5 version. Any idea how this can be fixed? Thanks!

**Comment by karlbunch** [comment]
Sorry it's been a while since I dug into this, it worked with the version I was running.  Maybe they made changes? I would look at their code and see if you can figure out the same place I hooked it before.
